### ISSUE TITLE
If there someone could tell me how to install fasm in windows?

### ISSUE THREAD

**Issue by the-centry** [SymbiFlow/fasm#66]
`
running build
running build_py
running egg_info
writing fasm.egg-info\PKG-INFO
writing dependency_links to fasm.egg-info\dependency_links.txt
writing entry points to fasm.egg-info\entry_points.txt
writing requirements to fasm.egg-info\requires.txt
writing top-level names to fasm.egg-info\top_level.txt
reading manifest file 'fasm.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs\_*'
no previously-included directories found matching 'docs\env'
warning: no previously-included files matching '.git' found anywhere in distribution
warning: no previously-included files found matching '.gitmodules'
warning: no previously-included files found matching 'update_version.py'
no previously-included directories found matching 'third_party'
no previously-included directories found matching '.github'
no previously-included directories found matching '__pycache__'
writing manifest file 'fasm.egg-info\SOURCES.txt'
running build_ext
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /mingw64/bin/cc.exe
-- Check for working C compiler: /mingw64/bin/cc.exe - works
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /mingw64/bin/c++.exe
-- Check for working CXX compiler: /mingw64/bin/c++.exe - works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:34 (find_library):
  Could not find ANTLR4_RUNTIME using the following names: antlr4-runtime

-- Configuring incomplete, errors occurred!
See also "/c/userdata/code/EDA/symbiflow/env/fasm/build/temp.win-amd64-3.8/Release/CMakeFiles/CMakeOutput.log".
See also "/c/userdata/code/EDA/symbiflow/env/fasm/build/temp.win-amd64-3.8/Release/CMakeFiles/CMakeError.log".
Failed to build ANTLR parser, falling back on slower textX parser. Error:
 Command '['cmake', 'C:\\userdata\\code\\EDA\\symbiflow\\env\\fasm\\src', '-DCMAKE_INSTALL_PREFIX=C:\\userdata\\code\\EDA\\symbiflow\\env\\fasm\\build\\lib.win-amd64-3.8\\fasm/parser', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\userdata\\code\\EDA\\symbiflow\\env\\fasm\\build\\lib.win-amd64-3.8\\fasm/parser', '-DPYTHON_EXECUTABLE=C:\\software\\miniconda3\\python.exe', '-DANTLR_RUNTIME_TYPE=shared', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "setup.py", line 103, in run
    super().run()
  File "C:\software\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\software\miniconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\software\miniconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\software\miniconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 185, in build_extension
    subprocess.check_call(
  File "C:\software\miniconda3\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\userdata\\code\\EDA\\symbiflow\\env\\fasm\\src', '-DCMAKE_INSTALL_PREFIX=C:\\userdata\\code\\EDA\\symbiflow\\env\\fasm\\build\\lib.win-amd64-3.8\\fasm/parser', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\userdata\\code\\EDA\\symbiflow\\env\\fasm\\build\\lib.win-amd64-3.8\\fasm/parser', '-DPYTHON_EXECUTABLE=C:\\software\\miniconda3\\python.exe', '-DANTLR_RUNTIME_TYPE=shared', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
`

**Comment by the-centry** [comment]
After install java,and the error just like [https://github.com/SymbiFlow/fasm/issues/65](https://github.com/SymbiFlow/fasm/issues/65)
I found that it use the env of mysys,and I change the env to vs,error happened just like here:
`
Failed to build ANTLR parser, falling back on slower textX parser. Error:
 Command '['cmake', '--build', '.', '--config', 'Release']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "setup.py", line 103, in run
    super().run()
  File "C:\software\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\software\miniconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\software\miniconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\software\miniconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 189, in build_extension
    subprocess.check_call(
  File "C:\software\miniconda3\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release']' returned non-zero exit status 1
`
